# Disable git proxy and url rewrites for this CocoaPods run
ENV['http_proxy'] = nil
ENV['https_proxy'] = nil
ENV['HTTP_PROXY'] = nil
ENV['HTTPS_PROXY'] = nil
ENV['no_proxy'] = '*'
ENV['NO_PROXY'] = '*'

system("git config --local http.proxy ''")
system("git config --local https.proxy ''")
system("git config --global url.'https://github.com/'.insteadOf 'http://github.com/' >/dev/null 2>&1")
system("git config --global url.'https://github.com/'.insteadOf 'git://github.com/' >/dev/null 2>&1")

# Force Git subprocesses to use HTTPS for github.com via environment variables in CocoaPods
ENV['GIT_CONFIG_COUNT'] = '2'
ENV['GIT_CONFIG_KEY_0'] = 'url.https://github.com/.insteadOf'
ENV['GIT_CONFIG_VALUE_0'] = 'http://github.com/'
ENV['GIT_CONFIG_KEY_1'] = 'url.https://github.com/.insteadOf'
ENV['GIT_CONFIG_VALUE_1'] = 'git://github.com/'



platform :ios, '13.0'

# connectivity_plus v6.x requires static frameworks but NOT global use_modular_headers.
# Using global use_modular_headers! causes connectivity_plus module to be invisible
# at compile time (GeneratedPluginRegistrant.m error: Module not found).
use_frameworks! :linkage => :static

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found. Run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
end
